### ISSUE TITLE
[BUG] Broken link at https://palkerecsenyi.github.io/magic/documentation/

### ISSUE THREAD

**Issue by devcurmudgeon** [palkerecsenyi/magic#35]
## Section(s)
- Documentation

## Type
**bug report**.

## Description
The following link (under Examples) is 404
https://palkerecsenyi.github.io/magic/documentation/example

**Comment by palkerecsenyi** [comment]
Sorry for the delays - The examples section is currently being created. I will add a message in the next release.

**Comment by palkerecsenyi** [comment]
Please see the https://github.com/palkerecsenyi/magic/tree/add-examples branch for fixes to this issue.

**Comment by palkerecsenyi** [comment]
Examples added and bug fixed. See #43
