### ISSUE TITLE
Feature request: Titles

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/magic#4]
The navbar of a page is styled and formatted correctly, especially with the SVG logos, however, for sites without logos, a style for a large "page title" element class would be ideal.

@tti0

**Comment by palkerecsenyi** [comment]
Will be added

**Comment by palkerecsenyi** [comment]
Feature added: you can have the following code for your navbar (svg functionality not affected):
~~~~
<nav>
  <a class="nav-brand-text">
    Brand
  </a>
  <ul class="nav-items">
    ...
  </ul>
</nav>
~~~~
Current support is only in non-minified standard.css in the development branch, will be merged with master later.
This update also added button colours:
~~~~
<button class="btn btn-default">
<button class="btn btn-yellow">
<button class="btn btn-red">
<button class="btn btn-green">
~~~~
For all code changes, see https://github.com/palkerecsenyi/magic/commit/e1c6416d3dd1da50be0b167068aecc4e6748e9f8
